### ISSUE TITLE
getBucket() is dependant upon logbox

### ISSUE THREAD

**Issue by christierney402** [coldbox-modules/s3sdk#14]
Unable to use as standalone due to the logbox dependency.

When running getBucket() method:

**Error:**
variable [LOG] doesn't exist

**Line:**
897: if( log.canDebug() ){

**Comment by Daemach** [comment]
Bit me too.

**Comment by jordanclark** [comment]
This should be fixed in #13 which has a logbox "polyfill" for those of us that don't use coldbox.
