### ISSUE TITLE
Developer setup documentation

### ISSUE THREAD

**Issue by sbleon** [coldbox-modules/s3sdk#17]
Hi! Thanks for creating this great resource! I've had some success with it so far, but need to make some additions. First, I need to be able to run the test suite!

How do I get the test suite running locally? I've been trying to follow the direction in `.travis.yml`, and I've managed to get the server started and get to the test runner, but I'm getting an error "Could not find a Java System property or Env setting with key [AWS_ACCESS_KEY].", even though I've populated my `.env` file per the example. I can help write some docs for this if someone is able to help me over the hurdles.

**Comment by sbleon** [comment]
I've started some documentation here: https://github.com/singlebrook/s3sdk/blob/dev_setup/dev_setup.md

**Comment by bdw429s** [comment]
Added here
https://github.com/coldbox-modules/s3sdk/blob/development/dev_setup.md
