### ISSUE TITLE
AWS reports incorrect signatures on CF11

### ISSUE THREAD

**Issue by sbleon** [coldbox-modules/s3sdk#23]
AWS reports that signatures are incorrect for many operations in the test suite when running CF11.

I've verified that the signing code in Sv4Util.cfc produces the same output with CF11, CF2016, and Lucee 4.5 and 5. So, the problem must be somewhere in the `S3Request()` method. That's as far as I've gotten so far.

**Comment by bdw429s** [comment]
@sbleon Do you still have this issue?  I've seen this error before, but it was usually my fault such as when I include a leading slash in my uri path or a double slash.

**Comment by sbleon** [comment]
I don't know. We don't use CF11 any more (and hopefully no-one else does either) so I don't particularly care about supporting it. We can close this as far as I'm concerned.

Thanks for cleaning up these issues, Brad!

**Comment by bdw429s** [comment]
OK, thanks. Re-open an issue if you run into this again.
