### ISSUE TITLE
Having an issue with downloading pdfs using the downloadObject() method

### ISSUE THREAD

**Issue by DavidWard98** [coldbox-modules/s3sdk#30]
Hey!
I am having an issue when I download a pdf from my s3 bucket my pdf reader says "There was an error while reading a stream." 
My code to download the pdf looks like this `s3sdk.downloadObject(uri="pathToFile", filePath = "#getTempDirectory()");`
I am using snapshot 4.6.0.
I have a feeling it has something to do with the encoding but I'm not sure where to look to fix the issue.

Thanks,
David

**Edit**: I tested with a plain text file and the download worked fine. Also tested with an image and did not work.

**Comment by lmajano** [comment]
@DavidWard98 I need more info.   Maybe you are not setting the right content type so your browser can read it.  Is the file downloading?

**Comment by DavidWard98** [comment]
The file is downloading - I'm just trying to save it to disk. I can get the file to save to disk but I am unable to open it in the correct format. Plain text downloads, saves and can be opened fine. Anything more complex (image, pdf, excel sheet) is unable to be opened.

I am trying to do a file download through an API
Client requests the file -> API Downloads file from s3 (using coldbox s3 module) -> API then serves file to Client

Thanks

**Comment by DavidWard98** [comment]
Hey,
Instead of using the downloadObject function I used the updated getAuthenticatedURL function from this branch, [leon-sigv4-get-requests](https://github.com/coldbox-modules/s3sdk/tree/leon-sigv4-get-requests). The downloading the file from the URL.
