### ISSUE TITLE
Special characters not allowed in key names

### ISSUE THREAD

**Issue by sethstone** [coldbox-modules/s3sdk#6]
I'm finding that special characters such as " ", "(", and ")" cause putObject() to fail with errors like this: 

`Code: SignatureDoesNotMatch\nMessage: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

I modified the file name in AmazonS3Spec.cfc `"can store a new object"` to be "example(test).txt" and "example test.txt" and both failed whereas "exampletest.txt" was put successfully.

I tried pre-urlencoding it including the custom methodology defined here:   https://www.bennadel.com/blog/2656-url-encoding-amazon-s3-resource-keys-for-pre-signed-urls-in-coldfusion.htm  
But still no luck.

**Comment by bdw429s** [comment]
This should be fixed on the latest version now
