### ISSUE TITLE
Error when providing 'prefix' to getBucket()

### ISSUE THREAD

**Issue by RickGroenewegen** [coldbox-modules/s3sdk#9]
Hello,

I'm trying to get a bucket listing using getBucket(), while trying to pass the 'prefix' parameter:

` var list = s3.getBucket(bucketName = "mybucket", prefix = "/myfolder");`

When I attempt to do so I receive the following error:

```
Type: S3SDKError 
Messages: Error making Amazon REST Call Code: InvalidArgument\nMessage: 
Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, 
Signature query string parameter or the Authorization header should be specified
```

When I try the same call without the 'prefix' the call succeeds and I get my bucket listing. However because of the huge amount of items in the bucket I would like to use the prefix to filter.

**Comment by lmajano** [comment]
@elpete any insight into this issue?

**Comment by elpete** [comment]
Can you paste a full stack trace, please, @RickGroenewegen?
